### ISSUE TITLE
Fortran runtime error: Array bound mismatch for dimension 3 of array 'gwann' (601/15)

### ISSUE THREAD

**Issue by wanyuloo** [nakib/elphbolt#154]
Description:
While attempting to compute gk_qpath, the calculation was interrupted due to a Fortran runtime error related to array bounds mismatch. Specifically, the error message indicates an issue with the third dimension of the array gwann.
Error Message:
Fortran runtime error: Array bound mismatch for dimension 3 of array 'gwann' (601/15)
Context:
I am running the gk_qpath calculation, and the error occurs during the process. Based on the error message, it appears that the array gwann is expected to have a size of 15 for the third dimension, but the actual size encountered during the calculation is 601, causing a mismatch and interrupting the execution.
The issue arises consistently and halts the computation.
Steps Taken:
I have provided highsympath.txt and initialk.txt files as input, and the calculation proceeds up until this error occurs.
I have verified the input files and the initial setup, but the issue persists.

**Comment by nakib** [comment]
Dear wanyloo,

Thanks for writing. I have not encountered this issue before. I will need to see your output file to understand what is happening.

Best,
Nakib

**Comment by wanyuloo** [comment]
In my previous inquiry, I encountered a Fortran runtime error when calculating a specific material using elphbolt. To further troubleshoot, I decided to run the official silicon example from the elphbolt website. Unfortunately, the same issue occurred.
The error message and output file are as follows：
[error message.log](https://github.com/user-attachments/files/17258092/error.message.log)
[output.log](https://github.com/user-attachments/files/17258094/output.log)

**Comment by nakib** [comment]
Thanks. Your output shows several instances of `Number of coarray images =     1`, from which it seems to me that your coarray installation is faulty. The quantity `gwann` is distributed over several coarray images and without a proper installation of coarrays, this error is inevitable.

I am moving this to the discussion section.

Best,
Nakib
