### ISSUE TITLE
EPW modified source for the ~Quantum Espresso v7.0~ suite

### ISSUE THREAD

**Issue by qiuzhanjun** [nakib/elphbolt#68]
I am using the newest QE v7.0 and EPW v5.4. I have modified the EPW source code files according to the files of directory EPW/src/ but failed, due to the changes of ndegen_g. Is it possible to provide the modified EPW v5.4 code after the revision of this version?

**Comment by nakib** [comment]
Hi @qiuzhanjun. Thanks for using elphbolt and for your question! Would you be able to provide more information? For example, did you replace the whole file ephwann_shuffle.f90 of your version of EPW with the one provided with elphbolt? If yes, could you please try for this file adding just the lines 417-458 from elphbolt's version to your version of EPW right below line 389? Let me know if this solves your issue.

Best,
Nakib

**Comment by qiuzhanjun** [comment]
I appreciate your answer. According your advice, I recompiled the epw. Fortunately, it worked and didn't report an error. Next I'll test if it can print out the required files. I will give the feedback later.
